runner: docker://alpine:latest

jobs:
  distckeck-gcc:
    environment:
      - TARGET=distcheck
      - CC=gcc
  valgrind-gcc:
    environment:
      - TARGET=valgrind
      - CC=gcc

script: |
  apk add --no-cache git gcc musl-dev cmocka-dev bash curl coreutils autotools automake libtool
  curl -sSf https://yatr.rgm.io/run.sh | bash
