if(NOT CPACK_SOURCE_INSTALLED_DIRECTORIES)
    file(INSTALL
        "${CPACK_RESOURCE_FILE_LICENSE}"
        "${CPACK_RESOURCE_FILE_README}"
        DESTINATION "${CMAKE_INSTALL_PREFIX}"
    )
endif()
